# Generated by Django 5.1.7 on 2025-04-16 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lesson_lessoncontent_contentblock_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='max_score',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Максимальная оценка'),
        ),
    ]
