# Generated by Django 5.1.7 on 2025-04-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contentblock_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
